apiVersion: v1
kind: Service
metadata:
  name: minecraft-admin
  namespace: minecraft
spec:
  selector:
    app: minecraft-admin
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      name: ssh
  type: ClusterIP
