apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minecraft-ppz-ingress
  ingressClassName: nginx
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    external-dns.alpha.kubernetes.io/hostname: minecraft-ppz.wittnerlab.com
    external-dns.alpha.kubernetes.io/target: a43b34e6-c752-44d1-99a5-cefa29a1fe53.cfargotunnel.com
spec:
  rules:
    - host: minecraft-ppz.wittnerlab.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minecraft-ppz-service
                port:
                  number: 80