apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-ingress-nginx
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: ingress-nginx
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.14.0
      helm:
        values: |
          watchIngressWithoutClass: true # Permet de regarder les ingress sans classe
          controller:
            service:
              type: ClusterIP # Type de service
            ingressClassResource:
              default: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
