global:
  domain: argocd.wittnerlab.com
server:
  ingress:
    enabled: true
    annotations:
      ingressClassName: nginx
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      external-dns.alpha.kubernetes.io/hostname: argocd.wittnerlab.com
      external-dns.alpha.kubernetes.io/target: 9110d4dd-b637-4907-8ff3-cd54a0ddfbc8.cfargotunnel.com
      #nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      #nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      #nginx.ingress.kubernetes.io/service-upstream: "true"
      nginx.ingress.kubernetes.io/proxy-ssl-verify: "false" # Disable SSL verification for self-signed certs
      #nginx.ingress.kubernetes.io/ssl-passthrough: "true" # Necessary for ArgoCD to work behind nginx with TLS
      #nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" # Necessary for ArgoCD to work behind nginx with TLS
    #tls: true # Enable TLS termination
    pathType: Prefix
    path: /
  data:
    server.insecure: "true" # Disable TLS verification for self-signed certs
