---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: app-minecraft-common
  namespace: flux-system
resources:
  - common/kustomization.yaml
  - ppz/kustomization.yaml
---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: app-minecraft-ppz
#   namespace: flux-system
# spec:
#   interval: 1m0s
#   path: ./gitops/apps/minecraft/ppz
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: app-minecraft-nohu
#   namespace: flux-system
# spec:
#   interval: 1m0s
#   path: ./gitops/apps/minecraft/nohu
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
